### ISSUE TITLE
Icon request for ignore files

### ISSUE THREAD

**Issue by dohun0310** [pandier/intellij-discord-rp#46]
Add an icon for ignorefile(like .gitignore, .dockerignore, etc)
<img width="232" alt="image" src="https://github.com/pandier/intellij-discord-rp/assets/63141348/a1b0cfba-7999-4c3b-b457-14fdd05cd95d">
<img width="277" alt="image" src="https://github.com/pandier/intellij-discord-rp/assets/63141348/388837b9-a544-4950-8b82-a1ba054a7843">

**Comment by pandier** [comment]
I also think that the default icon is enough for ignore files, but you might have a different opinions.

**Comment by dohun0310** [comment]
<img width="223" alt="image" src="https://github.com/pandier/intellij-discord-rp/assets/63141348/68764326-761d-467f-a7cb-b9f5368b16ca">
intellij handles four ignore files.
![image](https://github.com/pandier/intellij-discord-rp/assets/63141348/26ca2d02-9cac-4f20-9a32-f80880b96de4)
I thought it would be nice to see this, but that would be nice too.

**Comment by dohun0310** [comment]
And I think new future(Application mode) is not work
<img width="1728" alt="image" src="https://github.com/pandier/intellij-discord-rp/assets/63141348/4e137713-c251-471b-ad23-39280ccba51a">

**Comment by pandier** [comment]
The primary usage of Application mode is for privacy reasons. You can change the display mode per project, so that when you don't want to show a secret project, you can only show the application using the Application mode. The reason it doesn't work for just the application opened is that the IntelliJ Platform SDK doesn't allow running any code on application startup, only when opening a project.

**Comment by dohun0310** [comment]
Oh I guess that's not what I was thinking. Anyway, this feature is very cool. Thank you.

**Comment by pandier** [comment]
Done, will be avalible in **1.1** release.
