### ISSUE TITLE
discord name tag settings in intellij

### ISSUE THREAD

**Issue by Shihyeon** [pandier/intellij-discord-rp#53]
### What's missing?

can i set the intellij name in the same location as the figure? using the `{app_full_name}` variable, etc.

![image](https://github.com/pandier/intellij-discord-rp/assets/76618619/b1c75646-b0bc-4329-b6ab-35b2527e6fd8)

**Comment by pandier** [comment]
You can create a new application with the desired name at the [Discord Developer Portal](https://discord.com/developers/applications), then copy the application id, enable "Custom application id" inside the plugin settings and paste the id into the field.

There's sadly no other way to do this because of Discord's limitations.
